### ISSUE TITLE
this package no longer works with node version 0.10.25 and npm 1.4.21 as stated in the readme

### ISSUE THREAD

**Issue by pariosa** [Kwaadpepper/msi-keyboard-CLI#20]
[~] node -v                                                                    
v0.10.25
[~] npm -v                                                                     
1.4.21
[~] sudo npm install msi-keyboard-cli -g                                       
npm WARN engine node-hid@0.5.2: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
-
> node-hid@0.5.2 install /usr/local/lib/node_modules/msi-keyboard-cli/node_modules/msi-keyboard/node_modules/node-hid
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: Cannot find module 'rimraf'
node-pre-gyp ERR! stack     at Function.Module._resolveFilename (module.js:338:15)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:280:25)
node-pre-gyp ERR! stack     at Module.require (module.js:364:17)
node-pre-gyp ERR! stack     at require (module.js:380:17)
node-pre-gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/msi-keyboard-cli/node_modules/msi-keyboard/node_modules/node-hid/node_modules/node-pre-gyp/lib/clean.js:8:10)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
node-pre-gyp ERR! stack     at Module.require (module.js:364:17)
node-pre-gyp ERR! System Linux 4.4.0-57-generic
node-pre-gyp ERR! command "node" "/usr/local/lib/node_modules/msi-keyboard-cli/node_modules/msi-keyboard/node_modules/node-hid/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/msi-keyboard-cli/node_modules/msi-keyboard/node_modules/node-hid
node-pre-gyp ERR! node -v v0.10.25
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! node-hid@0.5.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the node-hid@0.5.2 install script.
npm ERR! This is most likely a problem with the node-hid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-hid
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.4.0-57-generic
npm ERR! command "node" "/usr/local/bin/npm" "install" "msi-keyboard-cli" "-g"
npm ERR! cwd /home/ 
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0

**Comment by Kwaadpepper** [comment]
Could you try to install ```rimraf``` ``` sudo npm install -g rimraf```, i think a module i uses is missing a dependency. Let me know if this solves your problem.
